---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-ui
  template:
    metadata:
      labels:
        app: chatbot-ui
    spec:
      containers:
      - name: chatbot
        image: rainover922/chatbot:latest
        ports:
        - containerPort: 3000  

---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-ui-service
spec:
  selector:
    app: chatbot-ui
  ports:
  - protocol: TCP
    port: 80                 
    targetPort: 3000
  type: LoadBalancer

